[project]
name = "pyplanc"
version = "0.0.1"
requires-python = ">=3.10"


[build-system]
requires = ["scikit-build-core>=0.9", "pybind11", "numpy"]
build-backend = "scikit_build_core.build"

[tool.scikit-build]
minimum-version = "0.9"


[tool.scikit-build.cmake]
version = ">=3.16"

[tool.cibuildwheel]
build-frontend = "build"
skip = ["*-win*", "*-manylinux*_i686", "*-musllinux*_i686"]

[tool.cibuildwheel.macos]
environment = {MACOS_DEPLOYMENT_TARGET="10.14"}
before-all = [
    "echo \"buildfromsource always\" | tee -a /opt/local/etc/macports/macports.conf",
    "echo \"extra_env MACOS_DEPLOYMENT_TARGET\" | tee -a /opt/local/etc/macports/macports.conf",
    "port install armadillo hdf5 hwloc"
]
#before-all = "port install armadillo hwloc"
test-command = "echo 'installed'"


[tool.cibuildwheel.linux]
before-all = "yum install -y epel-release hwloc-devel && yum install -y hdf5-devel armadillo-devel"
test-command = "echo 'installed'"
repair-wheel-command = "LD_LIBRARY_PATH=/project/lib/ auditwheel repair -w {dest_dir} {wheel}"
manylinux-x86_64-image = "manylinux_2_28"
manylinux-pypy_x86_64-image = "manylinux_2_28"
manylinux-aarch64-image = "manylinux_2_28"
manylinux-pypy_aarch64-image = "manylinux_2_28"
musllinux-x86_64-image = "musllinux_1_2"
musllinux-aarch64-image = "musllinux_1_2"

[[tool.cibuildwheel.overrides]]
select = "*-musllinux*"
before-all = "apk add hwloc arnadillo hdf5"
