name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os: [ubuntu-latest, macos-13, macos-14]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache/restore@v4
        name: Restore MacPorts Cache
        id: cache
        if: runner.os == 'macOS'
        with:
          key: ${{runner.os}}=0
          path: /opt/local

      - uses: melusina-org/setup-macports@v1
        if: runner.os == 'macOS' && steps.cache.outputs.cache-hit != 'true'

      - uses: actions/cache/save@v4
        name: Save MacPorts Cache
        if: runner.os == 'macOS' && steps.cache.outputs.cache-hit != 'true'
        with:
            path: /opt/local/
            #manual increment until i figure out how to deal
            key: ${{runner.os}}-0

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.19.1
        # env:
        #   CIBW_SOME_OPTION: value
        #    ...
        # with:
        #   package-dir: .
        #   output-dir: wheelhouse
        #   config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

